sysinit: added fsck, root rw remount, local mounts

diff --git a/sysinit b/sysinit
--- a/sysinit
+++ b/sysinit
@@ -28,14 +28,18 @@ mountfs sysfs sys /sys 'noexec,nosuid,nodev'
 # src/shared/hashmap.c for calls to random_bytes(), which is
 # implemented in src/shared/random-util.c via calling dev_urandom()
 # which in turn calls getrandom(2)).
+#
+# seedrng needs rw rootfs to remove old seed file and save new one.
+# Until then we use /run for this and copy new seed to rootfs later.
 echo 'seeding crng'
-/lib/rc/sbin/seedrng
+cp -a /var/lib/seedrng /run
+/lib/rc/sbin/seedrng --seed-dir /run/seedrng
 
-echo 'starting coldplug'
 udevd -d
 # succeeded triggers don't mean successful coldplug, b/c a lot depends
 # on udevd processing uevents in background, but triggers take time,
 # so we don't wait and opportunistically run them in parallel
+echo 'starting coldplug'
 udevadm trigger --type=subsystems --action=add &
 udevadm trigger --type=devices --action=add &
 
@@ -55,11 +59,36 @@ modules()
 netmodules='af_packet ipv6'
 modules &
 
-echo 'setting hostname'
-hostname -F /etc/hostname &
-
 echo 'loading keymap'
 loadkmap </etc/keymap/keymap.bmap &
+
+# if fsck fails and we exit, init will run getty next and it shows
+# hostname, so set hostname now synchronously (it's fast)
+echo 'setting hostname'
+hostname -F /etc/hostname
+
+echo 'running fsck'
+# make sure fsck.ext4 exists, b/c busybox fsck doesn't return error
+# when it can't exec fsck.<fstype> program (it prints error though,
+# see _void_ execute() in e2fsprogs/fsck.c), util-linux fsck is fine
+if ! command -v fsck.ext4 >/dev/null; then
+	echo 'fsck.ext4 not found'
+	exit 1
+fi
+ret=0
+fsck -T -A -P -p || ret=$?
+# if check was ok or errors were corrected, then continue, otherwise
+# stop (see fsck return codes in fsck(8))
+[ $ret -lt 2 ] || exit 1
+
+# root must be mounted rw before starting 1) syslogd, b/c it appends
+# to /var/log/messages, 2) ifup, b/c udhcpc writes to /etc/resolv.conf
+echo 'remounting root rw'
+mount -n -o remount,rw /
+
+# copy new seed generated by seedrng back to rw rootfs
+rm -f /var/lib/seedrng/*
+mv /run/seedrng/* /var/lib/seedrng
 
 echo 'starting syslogd'
 syslogd -t &
@@ -77,6 +106,9 @@ net()
 	ntpd -N -p pool.ntp.org
 }
 net &
+
+echo 'mounting local filesystems'
+mount -n -a
 
 # set KERN_EMERG==0 msg level, so it's always printed on console even
 # when "quiet" param was passed to kernel
